name: Test Action
on: [push]

jobs:
  use-db-api:
    runs-on: ubuntu-latest
    name: Use Databricks API
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'  
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash   
      - name: Run Python script
        id: get-square
        run: python src/connect.py
        shell: bash
